# Generated by Django 4.1.5 on 2023-01-17 02:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Spell",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, null=True)),
                ("description", models.CharField(max_length=400, null=True)),
                ("cooldown", models.IntegerField(null=True)),
                ("source", models.CharField(max_length=100, null=True)),
                ("gameClass", models.CharField(max_length=100, null=True)),
                ("deck", models.CharField(max_length=100, null=True)),
                (
                    "keywords",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, max_length=100, null=True
                        ),
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "relatedCards",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, max_length=100, null=True
                        ),
                        null=True,
                        size=None,
                    ),
                ),
            ],
        ),
    ]
