# Generated by Django 4.1.5 on 2023-01-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spells", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="spell",
            name="encounter",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
