# Generated by Django 4.1.5 on 2023-01-17 15:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artifact",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, null=True)),
                ("gameClass", models.CharField(max_length=100, null=True)),
                ("rarity", models.CharField(max_length=100, null=True)),
                ("description", models.CharField(max_length=400, null=True)),
                (
                    "keywords",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, max_length=100, null=True
                        ),
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "relatedCards",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, max_length=100, null=True
                        ),
                        null=True,
                        size=None,
                    ),
                ),
                ("volatile", models.BooleanField(default=False, null=True)),
                ("upgraded", models.BooleanField(default=False, null=True)),
            ],
            options={
                "verbose_name_plural": "Artifacts",
            },
        ),
    ]
