# Generated by Django 4.1.5 on 2023-01-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "artifact_class",
                    models.CharField(
                        choices=[
                            ("The Hidden", "The Hidden"),
                            ("The Tempest", "The Tempest"),
                            ("The Enlightened", "The Enlightened"),
                            ("The Daughter of the Void", "The Daughter of the Void"),
                            ("Global", "Global"),
                        ],
                        max_length=100,
                    ),
                ),
                ("number", models.IntegerField()),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("Starter", "Starter"),
                            ("Common", "Common"),
                            ("Uncommon", "Uncommon"),
                            ("Rare", "Rare"),
                            ("Elite", "Elite"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name_plural": "Artifacts",
            },
        ),
    ]
