# Generated by Django 4.1.5 on 2023-01-16 23:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artifacts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artifact",
            name="artifact_class",
        ),
        migrations.RemoveField(
            model_name="artifact",
            name="number",
        ),
        migrations.AddField(
            model_name="artifact",
            name="gameClass",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="artifact",
            name="keywords",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=100, null=True),
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="artifact",
            name="relatedCards",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=100, null=True),
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="description",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="rarity",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
