# Generated by Django 4.1.5 on 2023-01-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artifacts", "0002_remove_artifact_artifact_class_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artifact",
            name="upgraded",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="artifact",
            name="volatile",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
