# Generated by Django 4.1.5 on 2023-01-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artifacts", "0003_artifact_upgraded_artifact_volatile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifact",
            name="description",
            field=models.CharField(max_length=400, null=True),
        ),
    ]
