# Generated by Django 4.1.5 on 2023-01-16 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("keywords", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="keywords",
            name="kNumber",
        ),
    ]
