# Generated by Django 4.1.5 on 2023-01-17 15:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, null=True)),
                ("gameClass", models.CharField(default="Global", max_length=100)),
                (
                    "type",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, max_length=100, null=True
                        ),
                        null=True,
                        size=None,
                    ),
                ),
                ("rarity", models.CharField(default="Common", max_length=100)),
                ("energy", models.CharField(max_length=2, null=True)),
                ("upgradedEnergy", models.CharField(max_length=2, null=True)),
                ("description", models.CharField(max_length=200, null=True)),
                ("upgradedDescription", models.CharField(max_length=200, null=True)),
                (
                    "keywords",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, max_length=100, null=True
                        ),
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "relatedCards",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, max_length=100, null=True
                        ),
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "upgradedKeywords",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, max_length=100, null=True
                        ),
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "upgradedRelatedCards",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, max_length=100, null=True
                        ),
                        null=True,
                        size=None,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
