# Generated by Django 4.1.5 on 2023-01-16 23:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="card",
            options={"ordering": ["id"]},
        ),
        migrations.RenameField(
            model_name="card",
            old_name="cEnergy",
            new_name="energy",
        ),
        migrations.RemoveField(
            model_name="card",
            name="cDesc",
        ),
        migrations.RemoveField(
            model_name="card",
            name="cDesc_Upgrade",
        ),
        migrations.RemoveField(
            model_name="card",
            name="cEnergy_Upgrade",
        ),
        migrations.RemoveField(
            model_name="card",
            name="cName",
        ),
        migrations.RemoveField(
            model_name="card",
            name="cNumber",
        ),
        migrations.RemoveField(
            model_name="card",
            name="cRarity",
        ),
        migrations.RemoveField(
            model_name="card",
            name="cType",
        ),
        migrations.AddField(
            model_name="card",
            name="description",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="card",
            name="gameClass",
            field=models.CharField(
                choices=[
                    ("The Tempest", "The Tempest"),
                    ("The Hidden", "The Hidden"),
                    ("The Daughter of the Void", "The Daughter of the Void"),
                    ("The Enlightened", "The Enlightened"),
                    ("Global", "Global"),
                ],
                default="Global",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="card",
            name="rarity",
            field=models.CharField(
                choices=[
                    ("Rare", "Rare"),
                    ("Common", "Common"),
                    ("Affliction", "Affliction"),
                    ("Uncommon", "Uncommon"),
                ],
                default="Common",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="relatedCards",
            field=models.ManyToManyField(blank=True, to="cards.card"),
        ),
        migrations.AddField(
            model_name="card",
            name="type",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=100, null=True),
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="upgradedDescription",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="card",
            name="upgradedKeywords",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=100, null=True),
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="upgradedRelatedCards",
            field=models.ManyToManyField(blank=True, to="cards.card"),
        ),
        migrations.AlterField(
            model_name="card",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name="card",
            name="keywords",
        ),
        migrations.AddField(
            model_name="card",
            name="keywords",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=100, null=True),
                null=True,
                size=None,
            ),
        ),
    ]
