# Generated by Django 4.1.5 on 2023-01-16 23:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_alter_card_options_rename_cenergy_card_energy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="gameClass",
            field=models.CharField(
                choices=[
                    ("The Daughter of the Void", "The Daughter of the Void"),
                    ("The Enlightened", "The Enlightened"),
                    ("The Tempest", "The Tempest"),
                    ("Global", "Global"),
                    ("The Hidden", "The Hidden"),
                ],
                default="Global",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="rarity",
            field=models.CharField(
                choices=[
                    ("Common", "Common"),
                    ("Rare", "Rare"),
                    ("Uncommon", "Uncommon"),
                    ("Affliction", "Affliction"),
                ],
                default="Common",
                max_length=100,
            ),
        ),
        migrations.RemoveField(
            model_name="card",
            name="relatedCards",
        ),
        migrations.RemoveField(
            model_name="card",
            name="upgradedRelatedCards",
        ),
        migrations.AddField(
            model_name="card",
            name="relatedCards",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=100, null=True),
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="upgradedRelatedCards",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=100, null=True),
                null=True,
                size=None,
            ),
        ),
    ]
