# Generated by Django 4.1.5 on 2023-01-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0007_alter_card_gameclass_alter_card_rarity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="gameClass",
            field=models.CharField(
                choices=[
                    ("Global", "Global"),
                    ("The Daughter of the Void", "The Daughter of the Void"),
                    ("The Hidden", "The Hidden"),
                    ("The Tempest", "The Tempest"),
                    ("The Enlightened", "The Enlightened"),
                ],
                default="Global",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="rarity",
            field=models.CharField(
                choices=[
                    ("Affliction", "Affliction"),
                    ("Common", "Common"),
                    ("Rare", "Rare"),
                    ("Uncommon", "Uncommon"),
                ],
                default="Common",
                max_length=100,
            ),
        ),
    ]
