# Generated by Django 4.1.5 on 2023-01-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0014_alter_card_gameclass_alter_card_rarity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="gameClass",
            field=models.CharField(default="Global", max_length=100),
        ),
        migrations.AlterField(
            model_name="card",
            name="rarity",
            field=models.CharField(default="Common", max_length=100),
        ),
    ]
